name: pytorch_sac_ae
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip :
    - termcolor
    - dm_control
    - git+https://ghproxy.com/https://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - wandb
