# choose useable config combination in readme.md
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
os : ubuntu
os_version : '20.04' # 18.04 16.04 
python : '3.9' # 3.9 3.7
pytorch : '1.12.1' # 1.11.0 1.10.2
cuda : '11.3' # 10.2 10.1 10.0 11.0 
cuda_flavor : devel # devel runtime